version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    depends_on:
      - mysql
  mysql:
    image: mysql:8-oracle
    container_name: mysql
    ports:
      - '3306:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=123
      - MYSQL_USER=user
      - MYSQL_PASSWORD=123
      - MYSQL_DATABASE=payroll-m3-db
    restart: always