name: Merge on Success

on:
  push:
    branches:
      - test/feature

jobs:
  merge:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Grant permission to Maven wrapper
        run: chmod -x ./mvnw

      - name: Build and test
        run: ./mvnw clean test

      - name: Merge into main
        if: ${{ success() }}
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"
          git checkout main
          git merge --no-ff ${{ github.ref }}
          git push origin main
